name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - prod
      - backend-setup
    paths:
      - 'auto_video_create_server/**'
      - '.github/workflows/deploy-lambda-prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      LAMBDA_ZIP: lambda.zip
      LAMBDA_FUNCTION_NAME: auto-create-video-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auto_video_create_server/requirements.txt -t python
          cp -r \
            auto_video_create_server/main.py \
            auto_video_create_server/api \
            auto_video_create_server/services \
            auto_video_create_server/crawler \
            auto_video_create_server/utils \
            python/
          cd python
          zip -r ../${LAMBDA_ZIP} . -x "*/__pycache__/*" -x "*.pyc"
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://$LAMBDA_ZIP \
            --region $AWS_REGION 
