name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main
      - backend-setup
      # 필요시 feature/* 등 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      LAMBDA_ZIP: lambda.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auto_video_create_server/requirements.txt -t python
          cp auto_video_create_server/main.py python/
          cd python
          zip -r ../${LAMBDA_ZIP} .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Move lambda.zip to infra
        run: mv lambda.zip infra/

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_env: ${{ github.ref_name }} # 예: main, backend-setup 등 브랜치명 환경변수로 전달 가능

      - name: Show API Gateway endpoint
        working-directory: infra
        run: terraform output api_endpoint 